<<<<<<< HEAD
=======
# fly.toml app configuration file generated for connecterra on 2026-01-09T20:27:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

>>>>>>> a5f09ec9dccd8d30ede7dc9fd7f96ea484b1e011
app = 'connecterra'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8080'
  DATABASE_URL = "sqlite:////data/db.sqlite3" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory_mb = 1024
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
<<<<<<< HEAD

[deploy]
  release_command = 'python manage.py migrate --noinput && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username=\"admin\").exists() or User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin123\")"'

[mounts]
  source = "connecterra_data"
  destination = "/data"

[processes]
  app = "gunicorn seu_projeto.wsgi:application --bind 0.0.0.0:8080"
=======
>>>>>>> a5f09ec9dccd8d30ede7dc9fd7f96ea484b1e011
